### PR TITLE
Update the pragma statements to use a newer version of solidity

### PR DESCRIPTION
**Pull request by eggplantzzz**

### CODE REVIEW

**Review by gnidan — APPROVED** [review]

**Review by Joshua678891011 — COMMENTED** [review]
Ill try it

**Comment by Joshua678891011** [comment]
If you got to keep em would be greT

**Comment by Joshua678891011** [comment]
Works

**Comment by Joshua678891011** [comment]
I would like to keep some

**Comment by Joshua678891011** [comment]
Fghhjkvf

**Comment by Joshua678891011** [comment]
3ddx vkk cd. V

**Comment by Joshua678891011** [comment]
I do it

**Comment by Joshua678891011** [comment]
Omg

**Comment by Joshua678891011** [comment]
Y

**Comment by Joshua678891011** [comment]
!

**Pull request merged**
