### PR TITLE
camelCase variable names, use of async/await, added comments

### PR DESCRIPTION
**Pull request by dstawinski**
Made use of async/await and arrow functions in `test/metacoin.js`. Also changed variables to const and names to camelCase to follow guidelines. Added some comments to improve readability.

### CODE REVIEW

**Comment by eggplantzzz** [comment]
@dstawinski This looks like a good update. Sorry for the delay in getting around to looking at this.

**Review by gnidan — APPROVED** [review]

**Comment by eggplantzzz** [comment]
@dstawinski Do you have time to resolve this conflict? If so we can merge this soon. The requires were just updated to use the preferred syntax of requiring the contract name rather than the file. If you have any ?'s then let me know.

**Comment by eggplantzzz** [comment]
Also if you don't have time let me know and I'll go ahead and resolve the conflict.

**Comment by dstawinski** [comment]
Hello, sorry for delay as it was quick conflict but I hadn't seen the mail till today.

**Comment by eggplantzzz** [comment]
Thanks again @dstawinski !

**Pull request merged**
