### PR TITLE
Support Truffle v4.1.15

### PR DESCRIPTION
**Pull request by ecouffes**
**Issue**
https://github.com/truffle-box/metacoin-box/issues/12

**description**
support Truffle v4.1.15

### CODE REVIEW

**Comment by eggplantzzz** [comment]
@ecouffes Thanks, this looks good!

**Comment by eggplantzzz** [comment]
Oh, one thing that got missed...will you also please update the pragma statement for the solidity test as well in `test/TestMetacoin.sol`?

**Comment by ecouffes** [comment]
@eggplantzzz 
Thank you for pointing it out!
I have also updated the pragma statement in `test/TestMetacoin.sol`.

**Comment by adrianmcli** [comment]
lgtm, thx everyone.

**Pull request merged**
